import asyncio
import json

from playwright.async_api import async_playwright

from automation.replay import ReplayEngine


async def main():

    # Load the artifact generated by discovery
    with open(
        "artifacts/discovered_account_balance.json",
        "r",
        encoding="utf-8",
    ) as file:
        artifact = json.load(file)

    # Test successful account balance replay
    # Maya Patel - Checking account
    inputs = {
        "member_id": "12345",
        "account_type": "Checkings",
    }

    

    print("\nINPUTS USED FOR REPLAY:")
    print(inputs)

    print("\nGENERATED ARTIFACT FILL STEP:")
    print(artifact["steps"][1])

    async with async_playwright() as playwright:

        # Launch Chromium so we can watch the automation
        browser = await playwright.chromium.launch(
            headless=False
        )

        # Create browser page
        page = await browser.new_page()

        # Create replay engine
        engine = ReplayEngine(page)

        # Execute the discovered capability
        result = await engine.run(
            artifact=artifact,
            inputs=inputs,
        )

        print("\nREPLAY RESULT:")
        print(result)

        # Keep browser open so we can inspect the result
        input("\nPress Enter to close the browser...")

        await browser.close()


if __name__ == "__main__":
    asyncio.run(main())